### ISSUE TITLE
Bump base version constraints

### ISSUE THREAD

**Issue by danielsmw** [dmcclean/dimensional-codata#6]
Hi! I pulled out some old code of my from a year ago that uses dimensional-codata and tried upgrading my codebase to a newer version of GHC, but dimensional-codata complained that base was too new. Is there any compelling reason not to bump that up in the cabal file, or would newer versions of GHC be expected to cause problems?

Thanks for the great package, by the way. Believe it not, I use it *at* NIST. :)

**Comment by bjornbm** [comment]
Hi @danielsmw, great to hear that you are using this at NIST! 😃 

It seems life is interfering for @dmcclean at present. I prepared at pull request with a update of the upper bound but we will see if he finds time to merge it and upload to hackage. Other options to move forward with this with perhaps minimal effort for @dmcclean could be to:

1. [ ] Give me collaborator access to this repository so I can merge, and
2. [x] Add me or @danielsmw as a maintainer for the package on hackage ([link](https://hackage.haskell.org/package/dimensional/maintain)) so I can upload a new version (or edit upper bounds in metadata).
3. [ ] Edit the upper bounds in hackage metadata only ([link](https://hackage.haskell.org/package/dimensional/maintain)) without uploading a new version.

Strictly speaking only option 2 is necessary to move forward on this. Or even just asking the hackage “trustees” to perform the metadata revision which will be the way forward if @dmcclean doesn't respond or have time.

I hope you have been able to work around this while waiting and not been completely stuck waiting @danielsmw!

**Comment by dmcclean** [comment]
Hey guys.
I apologize for the delay in responding. Indeed I have been quite busy lately with children and a big deadline at the office.
I have merged this pull request, and added @bjornbm as a hackage maintainer.
My compiler installation is somewhat screwed up at the moment, so I don't think I can do the upload myself promptly. @bjornbm would you mind uploading it?

I too am excited to hear you have been using this at NIST.

@danielsmw As one of the few other known users of this package, do you have opinions on https://github.com/bjornbm/dimensional/issues/206 as applied to this package and to `dimensional` itself?

**Comment by bjornbm** [comment]
[Version 2014.0.0.2 uploaded to hackage](https://hackage.haskell.org/package/dimensional-codata-2014.0.0.2). Thanks @dmcclean!

**Comment by danielsmw** [comment]
@dmcclean thanks for the update, and @bjornbm for making the upgrade! 

As for the SI redefinition, I don't see a compelling reason that the structure of the dimensional library has to change very much. The redefinitions in terms of experimentally determined constants don't really affect how this package is used. If my application spits out "3.2 kg" as a result, it's my responsibility to understand what kg means. Two years ago, it would have meant something different than it means today, but I don't think capturing that change in meaning falls within the scope of this package. The dimensional calculus of how units are allowed to be combined, which seems like the main scope of dimensional to me, remains unchanged.

It may be of value to move the fundamental constants into dimensional itself, since they're now defined as part of SI and no longer reflect measurement results. It will not make sense for there to be another CODATA publication giving better numerical values for h, c, et cetera, so dimensional-codata will be sort of incorrectly named if the SI-defined constants stay there. Since dimensional-codata depends on dimensional anyway, maybe they could simply be re-exported.

It might be neat if you could do something like convert between SI units and the SI-defined constants within dimensional, which should now be possible in theory since they're linked by definition (by making Dimension a sum type, maybe?). That would be especially useful for certain physical calculations where you want to express something in "natural units". But I'm not sure how much use it would get in practice, so it's probably not worth the effort.

Anyway, that's all just my two cents. For what it's worth I don't work on units for fundamental constants at NIST, so I may not be any more informed that you guys. I work on neuromorphic and other alternative computing applications, so my use-case for dimensional is mostly for checking units in some numerical calculations/simulations of nanodevices I've written in Haskell, and so that I can make direct contact with experimental values.
